openapi: 3.0.0
servers: []
info:
  description: API zur Ankopplung konkreter Online-Dienste, die konkrete Verwaltungsleitsungen digitalisieren
  version: "1.0.0"
  title: Deutschland APP Backend Service
tags:
  - name: admin-service-provider
    description: Der Verwaltungsleistungsanbieter repräsentiert ein kokreter Online-Dienst, der eine konkrete Verwaltungsleitsung bereitstellt
paths:
  /service:
    get:
      tags:
        - app
      summary: searches inventory
      operationId: searchInventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: query
          name: searchString
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
        - in: query
          name: skip
          description: number of records to skip for pagination
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InventoryItem'
        '400':
          description: bad input parameter
    post:
      tags:
        - admin-service-provider
      summary: registriert die angegebene Verwaltungsleitsung
      operationId: registerService
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryItem'
        description: Inventory item to add
components:
  schemas:
    Form:
      type: object
      required:
        - serviceId
        - paymentRequired
        - fields
      properties:
        serviceId:
          type: string
          example: serv-halle-aufenthalt
        paymentRequired:
          type: boolean
          example: true
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
    Field:
      required:
        - field
        - type
      properties:
        field:
          anyOf:
            - $ref: '#/components/schemas/TextInfoField'
            - $ref: '#/components/schemas/SingleChoiceField'
            - $ref: '#/components/schemas/BigTextField'
            - $ref: '#/components/schemas/DateField'
            - $ref: '#/components/schemas/AttachmentField'
            - $ref: '#/components/schemas/MultipleChoiceField'
            - $ref: '#/components/schemas/TextInfoField'
            - $ref: '#/components/schemas/TextField'
            - $ref: '#/components/schemas/NumberField'
            - $ref: '#/components/schemas/RadioChoiceField'
            - $ref: '#/components/schemas/DocumentInfoField'
            - $ref: '#/components/schemas/EmailField'
            - $ref: '#/components/schemas/ImageField'
        type:
          type: string
          enum:  ["SingleChoiceField", "BigTextField", "DateField", "AttachmentField", "MultipleChoiceField", "TextInfoField", "TextField", "NumberField", "RadioChoiceField", "DocumentInfoField", "EmailField", "ImageField"]
          example: TextInfoField
      type: object
    TextInfoField:
      required:
        - text
      properties:
        text:
          type: string
          example: This is a text with useful info
      type: object
    TextField:
      required:
        - label
        - id
        - required
        - hint
      properties:
        label:
          type: string
          example: Your name
        id:
          type: string
          example: field-id-0
        required:
          type: boolean
          example: true
        hint:
          type: string
          example: Jane Doe
      type: object
    ImageField:
      properties:
        imageUri:
          type: string
          format: uri
          example: https://source.unsplash.com/random/1024x1024"
        label:
          type: string
          example: An image of something
      required:
        - imageUri
        - label
      type: object
    SingleChoiceField:
      properties:
        required:
          type: boolean
          example: true
        id:
          type: string
          example: field-id-0
        label:
          type: string
          example: Select something from the list
        hint:
          type: string
          example: Your choice
        options:
          type: array
          items:
            type: string
            example:  First Option
      required:
        - required
        - id
        - label
        - options
        - hint
      type: object
    BigTextField:
      properties:
        required:
          type: boolean
          example: true
        id:
          type: string
          example: field-id-0
        label:
          type: string
          example: Enter a big text
        hint:
          type: string
          example: Please write a lot of lines
      required:
        - required
        - hint
        - id
        - label
      type: object

    DateField:
      properties:
        required:
          type: boolean
          example: true
        id:
          type: string
          example: field-id-0
        label:
          type: string
          example: Enter your birthday
        hint:
          type: string
          example: 19.12.2000
      required:
        - required
        - hint
        - id
        - label
      type: object
    AttachmentField:
      properties:
        required:
          type: boolean
          example: true
        id:
          type: string
          example: field-id-0
        label:
          type: string
          example: Please attach your documents
        mimeType:
          type: string
          format: mime-type
          example: "application/pdf"
      required:
        - required
        - mimeType
        - id
        - label
      type: object

    MultipleChoiceField:
      properties:
        required:
          type: boolean
          example: true
        id:
          type: string
          example: field-id-0
        label:
          type: string
          example: Choose from multiple options
        options:
          type: array
          items:
            type: string
            example: First Option
      required:
        - required
        - id
        - label
        - options
      type: object
    NumberField:
      properties:
        required:
          type: boolean
          example: true
        id:
          type: string
          example: field-id-0
        label:
          type: string
          example: Enter your age
        hint:
          type: string
          example: 10
      required:
        - required
        - hint
        - id
        - label
      type: object
    RadioChoiceField:
      properties:
        required:
          type: boolean
          example: true
        id:
          type: string
          example: field-id-0
        label:
          type: string
          example: Please pick on of the choices
        options:
          type: array
          items:
            type: string
            example: First Option
      required:
        - required
        - id
        - label
        - options
      type: object

    DocumentInfoField:
      properties:
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'
        label:
          type: string
          example: This is set of documents
      required:
        - label
        - documents
      type: object

    EmailField:
      properties:
        required:
          type: boolean
          example: true
        id:
          type: string
          example: field-id-0
        label:
          type: string
          example: Your email address
        hint:
          type: string
          example: example@gmail.com
      required:
        - required
        - hint
        - id
        - label
      type: object
    Document:
      properties:
        mimeType:
          type: string
          format: mime-type
          example: application/pdf
        fileUri:
          type: string
          format: uri
          example: https://www.clickdimensions.com/links/TestPDFfile.pdf
        name:
          type: string
          example: Filename.pdf
      required:
        - mimeType
        - fileUri
        - name
      type: object